### ISSUE TITLE
new Crits install via bootstrap fails in the M2Crpto

### ISSUE THREAD

**Issue by nebdank** [crits/crits#735]
I have setup a virtual env on RHEL 6 and have installed python2.7 and have all the dependencies applied. However when it comes to putting m2crypto in, it fails with a swig error. Swig is installed, as is gcc etc.  

I put the following in roots profile to see if it woulld help:
SWIG_FEATURES=-cpperraswarn -includeall -I/usr/local/include -I/usr/include/openssl
LDFLAGS=-L/usr/local/lib
CFLAGS=-I/usr/local/include

The Error is: 
 swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c
  swig -python -D__x86_64__ -I/usr/local/include/python2.7 -I/usr/include -I/usr/include/openssl -includeall -modern -builtin -outdir build/lib.linux-x86_64-2.7/M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i
  swig error : Unrecognized option -builtin

 Swig is in directory structure: 
(CRITsVirtualEnv) [root@usmkpcti02 bin]# locate swig
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/__init__.py
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/__init__.pyc
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/__init__.pyo
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/setup.py
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/setup.pyc
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/setup.pyo
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/src
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/tests
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/src/example.c
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/src/example.i
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/src/zoo.cc
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/src/zoo.h
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/src/zoo.i
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/tests/test_example.py
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/tests/test_example.pyc
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/tests/test_example.pyo
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/tests/test_example2.py
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/tests/test_example2.pyc
/usr/lib64/python2.6/site-packages/numpy/distutils/tests/swig_ext/tests/test_example2.pyo

**Comment by systemxcom** [comment]
Same problem here.

building 'M2Crypto.__m2crypto' extension
    swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c
    swig -python -D__x86_64__ -I/usr/include/python2.7 -I/usr/include -I/usr/include/openssl -includeall -modern -builtin -outdir build/lib.linux-x86_64-2.7/M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i
    swig error : Unrecognized option -builtin
    Use 'swig -help' for available options.
    error: command 'swig' failed with exit status 1

**Comment by marcomafcorp** [comment]
I had the same issue try copying and pasting each line, ignore the blanks I didn't want to post the things that were there. I used the history command I hope it works for you as it did for me.

645  sudo apt-get install build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev
  646  
  647  pip install pillow
  648  pip install pycrypto
  649  
  650  sudo apt-get install libffi-dev

**Comment by frbapolkosnik** [comment]
M2Crypto is only used for totp in the core, so it's safe to comment it out if you're not going to use TOTP for authentication.

**Comment by cybercuffs** [comment]
Getting the same error: How to get around this issue? 

```
 building 'M2Crypto.__m2crypto' extension
    swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c
    swig -python -D__x86_64__ -I/usr/include/python2.6 -I/usr/include -I/usr/include/openssl -includeall -modern -builtin -outdir build/lib.linux-x86_64-2.6/M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i
    swig error : Unrecognized option -builtin
    Use 'swig -help' for available options.
    error: command 'swig' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of M2Crypto
Command "/usr/CRITsVirtualEnv/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-GdXfpE/m2crypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-yX8lk9-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-GdXfpE/m2crypto
Dependency installation failed!

        If M2Crypto failed to install, you might try to install the 
        OS-provided package with the package manager (apt-get/yum/brew)
        or try to adjust the CFLAGS, LDFLAGS, and SWIG_FEATURES
        with the right path to openssl headers and libs:
        sudo -E env LDFLAGS="-L/opt/local/lib"                     CFLAGS="-I/opt/local/include"                     SWIG_FEATURES="-cpperraswarn -includeall -I/opt/local/include"                     pip install M2Crypto

**Comment by cybercuffs** [comment]
@frbapolkosnik Where can I comment out the m2crypto?

**Comment by frbapolkosnik** [comment]
crits/core/totp.py and in requirements.txt

**Comment by frbapolkosnik** [comment]
I think that the #799 should fix that and more.

**Comment by mattulm** [comment]
I have tried commenting this out, but the install still fails at this point. I have also installed the package using apt-get, and no success either. I am on Ubuntu 16.04

**Comment by apolkosnik** [comment]
Can you post the exact error? Thanks

**Comment by mattulm** [comment]
Almost verbatim as above:

Dependency installation failed!

        If M2Crypto failed to install, you might try to install the 
        OS-provided package with the package manager (apt-get/yum/brew)
        or try to adjust the CFLAGS, LDFLAGS, and SWIG_FEATURES
        with the right path to openssl headers and libs:

**Comment by mattulm** [comment]
Sorry, added the "-H" flag on sudo, and things ran smoothly this time. I should be good now. Sorry for the hassle.

**Comment by LricoGaleano** [comment]
Hi there,

I am having similar problem when I run the the bootstrap script on a Ubuntu server. It fails on the part of  installing Python Dependencies and gives me the below error message

![Error](https://user-images.githubusercontent.com/51332101/71173471-b5c1cf00-225a-11ea-81b8-6fd553f16d72.JPG)

I am new to Linux - do you have any suggestion where and how to solve this error? Thank you in advance for your assistance.

**Comment by apolkosnik** [comment]
I think that at least for the core crits, I've replaced M2Crypto with pycrypto, so you should be able to just comment out the offending parts in the bootstrap as they are not needed.
