### ISSUE TITLE
bug in access control

### ISSUE THREAD

**Issue by NicHans1990** [crits/crits#926]
There is a bug in access control system using ACL. authorization and access control will not implemented on user login and save permissions, so that a user with any access, will have same access of previous login.

I have two users with different access. for example one with full access named "Uber admin" and another with less access named "analyst".
when I log on with "Uber admin" then I log out, then I log on with "analyst", analyst user will have the same access of previous user, it means analyst will have full access.
Vice versa if I logon with analyst then I log out and log in with "Uber admin" I will have access of previous user, it means Uberadmin will have less access such as analyst user.
I examined this problem with different browsers and different systems, problem persists! when login another system with the user with wrong access , user still have wrong access.

**Comment by mgoffin** [comment]
I submitted a PR: #931 

This seems to have fixed the issue on my end. Would you be willing to test it out and see if it solves your issue as well?

**Comment by mgoffin** [comment]
Have you been able to test this and confirm your issue is resolved?

**Comment by NicHans1990** [comment]
Thanks mike, sorry for my late answer, that time I reverted my server back to previous version with no roles,  now I installed the latest commit  from github but I couldn't login. I checked everything seems correct, I don't know is it my fault or this change caused it?

**Comment by mgoffin** [comment]
Someone made an issue that I'm trying to fix in another branch related to authentication. I'm not seeing the bug personally but I do see where the bug would manifest. It's possible you are hitting it as well.

**Comment by mgoffin** [comment]
I just merged some code into master. Let me know if that resolves your problem.

**Comment by NicHans1990** [comment]
thank mike, 
but I still have problem in login, it displays error message when username or password is wrong, but in case of correct username and password, return  HTTP error code 500.

**Comment by mgoffin** [comment]
I suspect it might be due to the reverting and database changes. I haven’t
been able to replicate the authentication issues. I’ve tried both an
UberAdmin and a very limited access user. Both can login and both have
their own ACL being enforced.

There might be an issue with the Django toolbar preventing authentication
as was noted in another issue, though I have that running and it seems fine
with the versions of the software that I have.

**Comment by apolkosnik** [comment]
If you take a look at the 500 response in Chrome's developer tools, it could get you the error message.

**Comment by nichans** [comment]
I installed a fresh Ubuntu and installed latest commit of crits from github, it still returns 500 reponse,
here is the details
![login error](https://user-images.githubusercontent.com/30946167/31338465-3de3b8ce-ad0c-11e7-9b26-dda78411e6bf.png)

**Comment by mgoffin** [comment]
Hmm. That seems like it might be related to a library conflict. Could you do a `pip freeze` and provide the output?

**Comment by nichans** [comment]
pip freeze
adium-theme-ubuntu==0.3.4
amqp==2.2.2
anyjson==0.3.3
billiard==3.5.0.3
biplist==1.0.2
celery==4.1.0
certifi==2017.7.27.1
chardet==3.0.4
dateutils==0.6.6
defusedxml==0.5.0
Django==1.8.18
django-celery==3.2.1
django-debug-toolbar==1.8
django-debug-toolbar-mongo==0.1.10
django-debug-toolbar-template-profiler==1.0.2
django-debug-toolbar-template-timings==0.7
django-debug-toolbar-vcs-info==1.2.0
django-mongoengine==0.2.1
django-tastypie==0.13.3
django-tastypie-mongoengine==0.4.7
future==0.16.0
idna==2.6
kombu==4.1.0
lxml==4.0.0
M2Crypto==0.27.0
mongoengine==0.8.8
olefile==0.44
pefile==2017.9.3
Pillow==4.3.0
pycrypto==2.6.1
pydeep==0.2
pyimpfuzzy==0.2
pymongo==2.8.1
pyparsing==2.2.0
python-dateutil==2.6.1
python-ldap==2.4.44
python-magic==0.4.6
python-mimeparse==1.6.0
pytz==2017.2
PyYAML==3.12
qrcode==5.3
requests==2.18.4
simplejson==3.11.1
six==1.11.0
sqlparse==0.2.4
typing==3.6.2
unity-lens-photos==1.0
urllib3==1.22
ushlex==0.99
vine==1.1.4
